[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["g++-12", "-std=gnu++2b", "-O2", "-DONLINE_JUDGE", "-DATCODER", "-Wall", "-Wextra", "-mtune=native", "-march=native", "-fconstexpr-depth=2147483647", "-fconstexpr-loop-limit=2147483647", "-fconstexpr-ops-limit=2147483647"] 
