name: build_pages

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
            
        - name: building
          run: |
            echo "<h1>Library</h1>" > index.html
            
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git fetch origin
            git checkout gh-pages
            git add .
            git commit -m "Update gh-pages"
            git push origin gh-pages
