name: build_pages

on:
    push:
        branches:
            -   main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
        
        -   name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.12
        
        -   name: build
            env:
                GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
            run: |
                python build_pages.py
                
                git config --global user.name "${{ github.actor }}"
                git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                git fetch origin
                git add .
                if [ -n "$(git status --porcelain)" ]; then
                    git commit -m "build pages"
                    git push origin main
                else
                    echo "No changes to commit"
                fi
