name: verify

on:
  push:
    branches:
      - main
  pull_request:

# ワークフロー内でリポジトリに push する場合、明示的に write 権限を要求できます。
permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install verification-helper
      run: pip3 install -U online-judge-verify-helper

    - name: Configure Git (no secrets)
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Run tests (C/C++)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify all --languages c,c++
