name: verify_mini

on:
    push:
        branches:
            -   main
    
    workflow_dispatch:

jobs:
    verify_m:
        runs-on: ubuntu-latest
    
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
    
        -   name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.12
    
        -   name: Install verification-helper
            run: pip3 install -U online-judge-verify-helper
    
        -   name: verify_mini
            run: |
                python verify_mini.py
