name: verify

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write   # GitHub Token がリポジトリに書き込む必要がある場合に便利

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install verification-helper
      run: pip3 install -U online-judge-verify-helper

    # Optional: Configure git to push using GH_PAT (if you set secrets.GH_PAT)
    - name: Configure git for pushing (optional)
      if: ${{ secrets.GH_PAT != '' }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"
        git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

    - name: Run tests (C/C++)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --languages c,c++
