name: verify_mini

on:
    push:
        branches:
            -   main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
        
        -   name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.12
        
        -   name: verify_mini
            run: |
                python verify_mini.py
